baseURL = '/'
languageCode = 'en-us'
paginate = 6
theme= "wedding"
title = 'Hayley & Robs Wedding'
 
[Menu]
  # Main Menu
  [[menu.Main]]
  name = "Info"
  url= "#service"
  weight = 1
  [[menu.Main]]
  name = "Gallery"
  url= "#gallery"
  weight = 2
  [[menu.Main]]
  name = "FAQ"
  url= "#faq"
  weight = 3
  [[menu.Main]]
  name = "Map"
  url= "#map"
  weight = 4

[params]
  aboutPageURL = "blog"
  contactLink = "contact"
  copyright = "Â© {year} <a href=\"https://digitalbarn.ca/\" target=\"_blank\">Digitalbarn Ltd. </a>"
  fabFormURL =  "https://fabform.io/f/u00kv3-"
  googleAnalytics = ""
  logo = "images/logo.png"
  footerlogo = "images/logo.png"
  footerDescription = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odit quia ab, natus fugiat voluptas saepe ipsum animi officiis in molestiae?"

  [params.address]
  address = "The Oxford Hills<br>324183 Mt Elgin Rd, <br>Mount Elgin, ON N0J 1N0"
  email = "hayleybathgate@gmail.com"
  openingDesc = ""
  openingHours = ""
  phone = "+(519) 000 0000"

  [params.map]
  APIkey = "AIzaSyD8v65dXeM-oPlmoxxCSG896yHR2dFHkD4"
  latitude = "42.96383168262409"
  longitude = "-80.78505017010458"
  pinImage = "images/pin.png"

  # Socail icons
  [[params.social]]
  icon = "ti-facebook"
  url = "https://www.facebook.com/"
  weight = 1
  [[params.social]]
  icon = "ti-twitter-alt"
  url = "https://twitter.com/"
  weight = 2
  [[params.social]]
  icon = "ti-dribbble"
  url = "https://dribbble.com/"
  weight = 3
  [[params.social]]
  icon = "ti-instagram"
  url = "https://www.instagram.com/"
  weight = 4
  
  
